import {
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BarChart3,
  BatteryFull,
  BellRing,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  Car,
  Check,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Database,
  FileText,
  FileWarning,
  Ghost,
  Hand,
  HardHat,
  HeartPulse,
  Home,
  Hourglass,
  Inbox,
  Info,
  KanbanSquare,
  ListChecks,
  LoaderCircle,
  Mail,
  MessageSquare,
  MessageSquareDashed,
  MessageSquareQuote,
  MessageSquareText,
  MessageSquareWarning,
  MoonStar,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  Plus,
  Repeat,
  Rocket,
  RotateCcw,
  Search,
  Settings2,
  ShieldCheck,
  SignalHigh,
  Sparkles,
  Sprout,
  Star,
  Thermometer,
  Timer,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UserCheck,
  UserPlus,
  Users,
  Voicemail,
  Wifi,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * ICON REGISTRY
 * -------------
 * Content files reference icons by string so the data stays serializable and
 * editable by non-developers. Icons are imported explicitly rather than with a
 * namespace import: `import * as Lucide` defeats tree-shaking and ships the
 * entire icon set (~600kB) into any client bundle that touches this file.
 *
 * Adding an icon to a content file? Add it to this map too.
 */
const registry: Record<string, LucideIcon> = {
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BarChart3,
  BatteryFull,
  BellRing,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  Car,
  Check,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Database,
  FileText,
  FileWarning,
  Ghost,
  Hand,
  HardHat,
  HeartPulse,
  Home,
  Hourglass,
  Inbox,
  Info,
  KanbanSquare,
  ListChecks,
  LoaderCircle,
  Mail,
  MessageSquare,
  MessageSquareDashed,
  MessageSquareQuote,
  MessageSquareText,
  MessageSquareWarning,
  MoonStar,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  Plus,
  Repeat,
  Rocket,
  RotateCcw,
  Search,
  Settings2,
  ShieldCheck,
  SignalHigh,
  Sparkles,
  Sprout,
  Star,
  Thermometer,
  Timer,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UserCheck,
  UserPlus,
  Users,
  Voicemail,
  Wifi,
  Workflow,
  Wrench,
  X,
  Zap,
};

type IconProps = {
  name: string;
  className?: string;
};

export function Icon({ name, className }: IconProps) {
  const Component = registry[name] ?? Circle;
  return <Component className={cn('h-5 w-5', className)} aria-hidden />;
}
